pipeline {
  agent any
  options { timestamps() }

  environment {
    IMAGE_UI = 'biblioflow-ui:prod'
    TEST_PORT = '8084'   // change if busy
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build UI image') {
      steps {
        sh 'docker build -t ${IMAGE_UI} .'
      }
    }

    stage('Smoke Test UI') {
      steps {
        sh '''
          docker rm -f ui_test || true
          docker run -d --name ui_test -p ${TEST_PORT}:80 ${IMAGE_UI}
          sleep 4
          curl -sSf http://localhost:${TEST_PORT}/ > /dev/null
        '''
      }
    }
  }

  post {
    always {
      sh 'docker rm -f ui_test || true'
    }
  }
}
